# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/FacultadInformatica-LinkedData/Curso2023-2024-DataScience/blob/master/Assignment4/course_materials/notebooks/Task07.ipynb

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2023-2024/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

# TO DO
q1 = """
    SELECT ?subclass
    WHERE {
        ?subclass rdfs:subClassOf ns:LivingThing .
    }
"""
# Visualize the results

for r in g.query(q1):
  print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
q2 = """
    SELECT ?individual
    WHERE {
        ?individual rdf:type/rdfs:subClassOf* ns:Person .
    }
"""

# Visualize the results
for r in g.query(q2):
    print(r)

"""**TASK 7.3: List all individuals of "Person" or "Animal" and all their properties including their class with RDFLib and SPARQL. You do not need to list the individuals of the subclasses of person**

"""

# TO DO

q3 =  """
  SELECT ?individual ?class ?property ?value
  WHERE {
    ?individual a ?class .
    ?individual ?property ?value
    FILTER (?class = :Person || ?class = :Animal)
}
"""
# Visualize the results
for r in g.query(q3):
    print("Individual:", r.individual)
    print("Property:", r.property)
    print("Value:", r.value)
    print()

"""**TASK 7.4:  List the name of the persons who know Rocky**"""

# TO DO
q4 = """
    SELECT ?person
    WHERE {
        ?person foaf:knows ns:RockySmith .
    }
"""

# Visualize the results
for r in g.query(q4):
    print(r.person)

"""**Task 7.5: List the entities who know at least two other entities in the graph**"""

# TO DO
q5 = """
    SELECT ?person
    WHERE {
        ?person foaf:knows ?other1 .
        ?person foaf:knows ?other2 .
        FILTER (?other1 != ?other2)
    }
"""

# Visualize the results
for r in g.query(q5):
    print(r.person)